apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: spedev
spec:
  schedule: "*/2 9-18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure